---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - dnsutils
      - curl
      - git
      - ca-certificates
    state: present
    update_cache: yes
    cache_valid_time: 3600
